apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-duckdb-data
  namespace: ecommerce-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

