apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: ecommerce-analytics
type: Opaque
stringData:
  username: ecommerce
  password: ecommerce-demo
  url: amqp://ecommerce:ecommerce-demo@rabbitmq:5672/%2F

